
                <fieldset>
                    <legend>Please confirm this action</legend>

                    <?php echo $this->messages() ?>

                    <?php
                    $form = $this->form;
                    $form->prepare();
                    ?>

                    <?php echo $this->form()->openTag($form) ?>

                        <?php echo $this->adminFormElement($form->get('from')) ?>
                        <?php echo $this->adminFormElement($form->get('id')) ?>
                        <?php echo $this->adminFormElement($form->get('token')) ?>

                        <div class="form-element">
                            <div class="form-inputs line-up">
                                <?php
                                $form->get('confirm')->setAttribute('class', 'btn btn-primary');
                                echo $this->formElement($form->get('confirm')) ?>
                            </div>
                        </div>
                    <?php echo $this->form()->closeTag() ?>

                </fieldset>
