<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <link rel="stylesheet" type="text/css" href="/css/admin.css" />
        <script type="text/javascript" src="/js/admin.js"></script>
    </head>

    <body class="yui-skin-sam" onLoad="document.getElementById('dynname').innerHTML=main.name.value;">

        <div id="top"><!-- Start top area -->

            <div class="title">Create: item</div>
            <?php echo $this->messages() ?>
            <div class="info"><img src="/images/required_star.png" alt="Required"> indicates required field</div>

        </div><!-- End top area -->

        <?php
        $form = $this->form;
        $form->setAttribute('name', 'main')->prepare();
        ?>

        <?php echo $this->form()->openTag($form) ?>

            <?php echo $this->adminFormElement($form->get('from')) ?>
            <?php echo $this->adminFormElement($form->get('provisionalTo')) ?>
            <?php echo $this->adminFormElement($form->get('provisionalBeneathMenuItemId')) ?>
            <?php echo $this->adminFormElement($form->get('token')) ?>

            <div id="stage"><!-- Start stage area -->

                <div class="white-box"><!-- Start fieldset -->
                    <div class="white-box-rounded-corner-top"><div></div></div>
                    <div class="white-box-content">
                        <div class="white-box-title">Settings</div>

                        <?php
                        $form->get('name')->setAttribute('onKeyUp', 'document.getElementById(\'dynname\').innerHTML=main.name.value;');
                        echo $this->adminFormElement($form->get('name'));
                        echo $this->adminFormElement($form->get('typeId'));
                        ?>

                    </div>
                </div><!-- End fieldset -->

            </div><!-- End stage area -->

            <div class="submit-area">

                <div class="form-element">
                    <div class="form-inputs line-up">
                        <?php
                        $form->get('create')->setAttribute('class', 'button');
                        echo $this->formElement($form->get('create'));
                        ?>
                    </div>
                </div>

            </div>

        <?php echo $this->form()->closeTag() ?>

    </body>
</html>
