<?php
$this->inlineScript()->appendScript("document.getElementById('dynname').innerHTML=main.name.value");
?>

        <div class="row">
            <div class="col-md-12">

                <h1>Create item</h1>

                <?php
                $form = $this->form;
                $form->setAttribute('name', 'main');
                $form->setAttribute('class', 'form-horizontal');
                $form->prepare();
                ?>

                <?php echo $this->form()->openTag($form) ?>

                    <?php echo $this->adminFormElement($form->get('from')) ?>
                    <?php echo $this->adminFormElement($form->get('provisionalTo')) ?>
                    <?php echo $this->adminFormElement($form->get('provisionalBeneathMenuItemId')) ?>
                    <?php echo $this->adminFormElement($form->get('token')) ?>

                    <fieldset>
                        <legend>Settings</legend>

                        <?php
                        $form->get('name')->setAttribute('onKeyUp', 'document.getElementById(\'dynname\').innerHTML=main.name.value;');
                        echo $this->adminFormElement($form->get('name'));
                        echo $this->adminFormElement($form->get('typeId'));
                        ?>

                    </fieldset>

                    <div class="form-group">

                        <div class="col-md-10 col-md-offset-2">
                            <?php
                            $form->get('create')->setAttribute('class', 'btn btn-primary');
                            echo $this->formElement($form->get('create'));
                            ?>
                        </div>

                    </div>

                <?php echo $this->form()->closeTag() ?>

            </div>
        </div>
