<?php
$this->inlineScript()->appendScript("document.getElementById('dynname').innerHTML=main.name.value");
?>

        <div class="row">
            <div class="col-md-12">

                <h1>Create: item</h1>

                <div class="info">
                    <img src="/images/required_star.png" alt="Required"> indicates required field
                </div>

                <?php
                $form = $this->form;
                $form->setAttribute('name', 'main')->prepare();
                ?>

                <?php echo $this->form()->openTag($form) ?>

                    <?php echo $this->adminFormElement($form->get('from')) ?>
                    <?php echo $this->adminFormElement($form->get('provisionalTo')) ?>
                    <?php echo $this->adminFormElement($form->get('provisionalBeneathMenuItemId')) ?>
                    <?php echo $this->adminFormElement($form->get('token')) ?>

                    <div class="white-box"><!-- Start fieldset -->
                        <div class="white-box-rounded-corner-top"><div></div></div>
                        <div class="white-box-content">
                            <div class="white-box-title">Settings</div>

                            <?php
                            $form->get('name')->setAttribute('onKeyUp', 'document.getElementById(\'dynname\').innerHTML=main.name.value;');
                            echo $this->adminFormElement($form->get('name'));
                            echo $this->adminFormElement($form->get('typeId'));
                            ?>

                        </div>
                    </div>

                    <div class="submit-area">

                        <div class="form-element">
                            <div class="form-inputs line-up">
                                <?php
                                $form->get('create')->setAttribute('class', 'button');
                                echo $this->formElement($form->get('create'));
                                ?>
                            </div>
                        </div>

                    </div>

                <?php echo $this->form()->closeTag() ?>

            </div>
        </div>
