<?php
if ($this->preview) :

    $url = $this->url('content', ['slug' => $this->itemName], [
        'query' => [
            'preview' => 'content',
        ],
    ]);

    $this->inlineScript()->appendScript("open_preview('{$url}')");

endif;

$script = <<<SCRIPT
$(function(){

    function updateCkEditors() {
        for ( instance in CKEDITOR.instances ) {
            CKEDITOR.instances[instance].updateElement();
        }
    }

    $(document).ready(function() {

        $('[data-preview-template-id]').click(function(event) {
            event.preventDefault();
            var templateId = $(this).data('preview-template-id');
            $('input[name="previewTemplateId"]').val(templateId);
            updateCkEditors();
            $(this).closest('form').submit();
        });
    });
});
SCRIPT;
$this->inlineScript()->appendScript($script);

$this->headScript()->appendFile('/ckeditor/ckeditor.js');
$this->headScript()->appendFile('/ckfinder/ckfinder.js');
?>

        <div class="row">
            <div class="col-md-12">

                <h1>Edit<?php echo ($this->titleSuffix) ? ' ' . $this->escapeHtml(strtolower($this->titleSuffix)) : '' ?>
                <?php echo $this->escapeHtml($this->typeName) ?> <small><?php echo $this->escapeHtml($this->itemName) ?></small></h1>

                <?php
                $form = $this->form;
                $form->setAttribute('name', 'main');
                $form->setAttribute('class', 'form-horizontal');
                $form->prepare();
                ?>

                <?php echo $this->form()->openTag($form) ?>

                    <?php echo $this->adminFormElement($form->get('from')) ?>
                    <?php echo $this->adminFormElement($form->get('id')) ?>
                    <?php echo $this->adminFormElement($form->get('partial')) ?>
                    <?php echo $this->adminFormElement($form->get('token')) ?>

                    <fieldset>
                        <legend>Notes</legend>
                        <p>
                            <?php if (empty($this->itemNotes)) : ?>
                            No notes found
                            <?php else : ?>
                            <?php foreach ($this->itemNotes as $note) : ?>
                            <?php echo $this->date($note->time, 'F j Y H:i') . ' - ' .
                            $this->escapeHtml($note->username) . ' - ' .
                            $this->escapeHtml($note->text) ?><br />
                            <?php endforeach; ?>
                            <?php endif; ?>
                        </p>
                    </fieldset>

                    <fieldset>
                        <legend>Content</legend>

                        <?php echo $this->adminFormElement($form->get('navText')) ?>

                        <?php if ($this->enableMetaFields) : ?>
                        <?php echo $this->adminFormElement($form->get('metaKeywords')) ?>
                        <?php echo $this->adminFormElement($form->get('metaDescription')) ?>
                        <?php endif; ?>

                        <?php echo $this->adminFormElement($form->get('title')) ?>

                        <?php if ($form->has('fields')) : ?>
                        <?php foreach ($form->get('fields')->getElements() as $element) : ?>
                        <?php echo $this->adminFormElement($element) ?>
                        <?php endforeach; ?>
                        <?php endif; ?>

                        <?php if ($form->has('parts')) : ?>
                        <?php if ($this->multipleParts) : ?>
                        <div id="ib_container" class="ib-container yui-navset">

                            <p>Number of parts <select class="ib-add-part-select">
                                    <option value="0" selected="selected">0</option>
                                    <?php for ($i = 1; $i <= 10; $i++) : ?>
                                    <option value="<?php echo $i ?>"><?php echo $i ?></option>
                                    <?php endfor; ?>
                                </select></p>

                            <ul id="ib_list" class="ib-draglist yui-nav">
                                <?php foreach ($form->get('parts')->getFieldsets() as $key => $part) : ?>
                                <li id="ib_list_item<?php echo $key ?>" class="ib-draglist-item<?php if ($form->get('selectedPart')->getValue() == $key) : ?> selected<?php endif; ?>"<?php if ($part->get('delete')->getValue()) : ?> style="display: none;"<?php endif; ?>><a href="#tab<?php echo $key; ?>"><em>&nbsp;</em></a></li>
                                <?php endforeach; ?>
                            </ul>

                            <?php echo $this->formHidden($form->get('selectedPart')->setAttribute('id', 'selected-part')); ?>

                            <div class="yui-content">
                         <?php endif; ?>

                                <?php foreach ($form->get('parts')->getFieldsets() as $key => $part) : ?>
                                <div id="ib_part<?php echo $key ?>" class="ib-part">

                                    <?php if ($this->multipleParts) : ?>
                                    <?php echo $this->formHidden($part->get('orderBy')) ?>
                                    <img class="ib-delete-part-icon" src="/images/icons/dustbin.png" alt="Dustbin icon" title="Delete part" />
                                    <?php echo $this->formHidden($part->get('delete')) ?>
                                    <?php endif; ?>

                                    <?php $count = 0; foreach ($part->getElements() as $element) : ?>
                                    <?php if ($element->getName() !== 'orderBy' && $element->getName() !== 'delete') : ?>
                                    <?php echo $this->adminFormElement($element) ?>
                                    <?php endif; ?>
                                    <?php $count++; endforeach; ?>

                                </div>
                                <?php endforeach; ?>

                        <?php if ($this->multipleParts) : ?>
                            </div>
                        </div>
                        <?php endif; ?>
                        <?php endif; ?>

                    </fieldset>

                    <fieldset>
                        <legend>Submit</legend>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-2">

                                <?php if (count($form->get('previewTemplateId')->getValueOptions())) : ?>

                                <?php echo $this->formHidden($form->get('previewTemplateId')); ?>

                                <div class="btn-group">
                                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Preview <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <?php foreach ($form->get('previewTemplateId')->getValueOptions() as $id => $option) : ?>
                                        <li><a data-preview-template-id="<?php echo $id ?>"><?php echo $option ?></a></li>
                                        <?php endforeach; ?>
                                    </ul>
                                </div>

                                <?php else : ?>

                                <?php
                                $form->get('preview')->setAttribute('class', 'btn btn-default');
                                echo $this->formElement($form->get('preview'));
                                ?>

                                <?php endif; ?>

                            </div>
                        </div>

                        <?php echo $this->adminFormElement($form->get('note')) ?>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-2">

                                <?php
                                $form->get('save')->setAttribute('class', 'btn btn-warning');
                                echo $this->formElement($form->get('save'));
                                ?>

                                <?php
                                $form->get('publish')->setAttribute('class', 'btn btn-success');
                                echo $this->formElement($form->get('publish'));
                                ?>

                            </div>
                        </div>

                    </fieldset>

                <?php echo $this->form()->closeTag() ?>

            </div>
        </div>
