<?php
use Boxspaced\CmsItemModule\Service\ItemService;

if ($this->preview) :

    $url = $this->url('content', ['slug' => $this->itemName], [
        'query' => [
            'preview' => 'publishing',
        ],
    ]);

    $this->inlineScript()->appendScript("open_preview('{$url}')");

endif;
?>

        <div class="row">
            <div class="col-md-12">

                <h1>
                    Publish
                    <span class="type"><?php echo $this->escapeHtml($this->typeName) ?></span>
                    <small><?php echo $this->escapeHtml($this->itemName) ?></small>
                </h1>

                <?php
                $form = $this->form;
                $form->setAttribute('name', 'main');
                $form->setAttribute('class', 'form-horizontal');
                $form->prepare();
                ?>

                <?php echo $this->form()->openTag($form) ?>

                    <?php echo $this->adminFormElement($form->get('from')) ?>
                    <?php echo $this->adminFormElement($form->get('id')) ?>
                    <?php echo $this->adminFormElement($form->get('partial')) ?>
                    <?php echo $this->adminFormElement($form->get('token')) ?>

                    <fieldset>
                        <legend>Notes</legend>

                        <div class="form-group">
                            <label class="col-md-2 control-label">&nbsp;</label>
                            <div class="col-md-10">
                                <p class="form-control-static">
                                    <?php if (empty($this->itemNotes)) : ?>
                                        No notes found
                                    <?php else : ?>
                                        <?php foreach ($this->itemNotes as $note) : ?>
                                            <?php
                                            echo $this->date($note->time, 'F j Y H:i') . ' - ' .
                                            $this->escapeHtml($note->username) . ' - ' .
                                            $this->escapeHtml($note->text)
                                            ?><br />
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </p>
                            </div>
                        </div>

                    </fieldset>

                    <fieldset>
                        <legend>Lifespan</legend>

                        <?php
                        $form->get('liveFrom')->setAttribute('class', 'live-from-datepicker');
                        echo $this->adminFormElement($form->get('liveFrom'));
                        ?>

                        <?php
                        $form->get('expiresEnd')->setAttribute('class', 'expires-end-datepicker');
                        echo $this->adminFormElement($form->get('expiresEnd'));
                        ?>

                    </fieldset>

                    <fieldset>
                        <legend>Settings</legend>

                        <?php echo $this->adminFormElement($form->get('name')) ?>
                        <?php echo $this->adminFormElement($form->get('colourScheme')) ?>

                        <?php
                        if ($this->teaserTemplateDescription) :
                            $currentDesc = $form->get('teaserTemplateId')->getOption('description');
                            $form->get('teaserTemplateId')->setOption('description', $currentDesc . $this->teaserTemplateDescription);
                        endif;
                        if (count($form->get('teaserTemplateId')->getValueOptions()) > 1) :
                            echo $this->adminFormElement($form->get('teaserTemplateId'));
                        else :
                            echo $this->formHidden($form->get('teaserTemplateId'));
                        endif;
                        ?>

                        <?php
                        $form->get('templateId')->setAttribute('onChange', 'submit_partial(this.form)');
                        if ($this->templateDescription) :
                            $currentDesc = $form->get('templateId')->getOption('description');
                            $form->get('templateId')->setOption('description', $currentDesc . $this->templateDescription);
                        endif;
                        if (count($form->get('templateId')->getValueOptions()) > 1) :
                            echo $this->adminFormElement($form->get('templateId'));
                        else :
                            echo $this->formHidden($form->get('templateId'));
                        endif;
                        ?>

                    </fieldset>

                    <fieldset>
                        <legend>Location</legend>

                        <?php
                        if (null !== $this->provisionalTo) :
                            $useProvisional = $form->get('useProvisional');
                            $useProvisional->setAttribute('onChange', 'submit_partial(this.form)');
                            echo $this->adminFormElement($useProvisional);
                        endif;
                        ?>

                        <?php if ($form->get('useProvisional')->isChecked()) : ?>
                        <div class="form-group">
                            <label class="col-md-2 control-label">To</label>
                            <div class="col-md-10">
                                <p class="form-control-static">
                                    <?php echo $this->escapeHtml($this->provisionalTo) ?>
                                </p>
                            </div>
                        </div>
                        <?php if ($this->provisionalBeneathMenuItem) : ?>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Menu position</label>
                            <div class="col-md-10">
                                <p class="form-control-static">
                                    <?php echo $this->escapeHtml($this->provisionalBeneathMenuItem) ?>
                                    <?php if ($this->provisionalBeneathMenuItem !== 'Top level') : ?>
                                    <-- Beneath
                                    <?php endif; ?>
                                </p>
                            </div>
                        </div>
                        <?php endif; ?>
                        <?php endif; ?>

                        <?php if (!$form->get('useProvisional')->isChecked()) : ?>

                        <?php
                        $form->get('to')->setAttribute('onChange', 'submit_partial(this.form)');
                        echo $this->adminFormElement($form->get('to'));
                        ?>

                        <?php if ($form->get('to')->getValue() === ItemService::PUBLISH_TO_MENU) : ?>
                        <?php echo $this->adminFormElement($form->get('beneathMenuItemId')); ?>
                        <?php endif; ?>

                        <?php endif; ?>

                    </fieldset>

                    <?php
                    $freeBlocks = $form->get('freeBlocks')->getFieldsets();
                    $blockSequences = $form->get('blockSequences')->getFieldsets();
                    ?>

                    <?php if ($freeBlocks || $blockSequences) : ?>
                    <fieldset>
                        <legend>Blocks</legend>

                        <?php foreach ($freeBlocks as $freeBlock) : ?>
                        <div class="form-group">
                            <label class="col-md-2 control-label"><?php echo $freeBlock->getLabel() ?></label>
                            <div class="col-md-10">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Block</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>
                                                <?php echo $this->formElement($freeBlock->get('id')); ?>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <?php endforeach; ?>

                        <?php foreach ($blockSequences as $blockSequence) : ?>

                        <?php

                        $idOptions = [];

                        foreach ($form->getBlockValueOptions() as $blockTypeName => $options) {
                            foreach ($options['options'] as $value => $label) {
                                $idOptions[$value] = $blockTypeName . ' ' . $label;
                            }
                        }

                        $idNameTpl = $blockSequence->getName() . '[blocks][#][id]';
                        $orderByNameTpl = $blockSequence->getName() . '[blocks][#][orderBy]';
                        $numCurrentBlocksName = $blockSequence->getName() . '[numCurrentBlocks]';
                        $numNewBlocksName = $blockSequence->getName() . '[numNewBlocks]';
                        $tableId = $this->adminFormElement()->nameToId($blockSequence->getName()) . '-en';
                        ?>

                        <div class="form-group">
                            <label class="col-md-2 control-label"><?php echo $blockSequence->getLabel() ?></label>
                            <div class="col-md-10">
                                <table class="table table-bordered collapse" id="<?php echo $tableId; ?>">
                                    <tbody></tbody>
                                </table>

                                <script type="text/javascript">

                                    <?php foreach ($blockSequence->get('blocks') as $sequenceBlock) : ?>

                                    $('#<?php echo $tableId; ?>').show();

                                    addRow(
                                    'saved',
                                    '<?php echo $this->adminFormElement()->nameToId($blockSequence->getName()) . '-en'; ?>',
                                    [
                                        '<?php echo $orderByNameTpl; ?>',
                                        '<?php echo $this->escapeJs($sequenceBlock->get('orderBy')->getValue()); ?>'
                                    ],
                                    [
                                        [
                                            'createBlockIdSelect',
                                            '<?php echo $idNameTpl; ?>',
                                            '<?php echo $this->escapeJs($sequenceBlock->get('id')->getValue()); ?>',
                                            [['', '']
                                            <?php foreach ($idOptions as $value => $label) : ?>
                                            ,['<?php echo $this->escapeJs($value); ?>', '<?php echo $this->escapeJs($label); ?>']
                                            <?php endforeach; ?>],
                                            false
                                        ]
                                    ],
                                    '<?php echo $this->adminFormElement()->nameToId($numCurrentBlocksName); ?>',
                                    '<?php echo $this->adminFormElement()->nameToId($numNewBlocksName); ?>',
                                    'en',
                                    'en',
                                    ['en']);

                                    <?php endforeach; ?>

                                    sortTable('<?php echo $this->adminFormElement()->nameToId($blockSequence->getName()) . '-en'; ?>', 0, 0, 'numeric', 'ASC');
                                </script>

                                <p><a class="btn btn-default" href="javascript:void(0)" onclick="$('#<?php echo $tableId; ?>').show(); addBlankRow(
                                        '<?php echo $this->adminFormElement()->nameToId($blockSequence->getName()) . '-en'; ?>',
                                        20,
                                        [
                                            '<?php echo $orderByNameTpl; ?>',
                                            ''
                                        ],
                                        [
                                            [
                                                'createBlockIdSelect',
                                                '<?php echo $idNameTpl; ?>',
                                                '',
                                                [
                                                    ['', '']
                                                    <?php foreach ($idOptions as $value => $label) : ?>
                                                    ,['<?php echo $this->escapeJs($value); ?>', '<?php echo $this->escapeJs($label); ?>']
                                                    <?php endforeach; ?>
                                                ],
                                                false
                                            ]
                                        ],
                                        '<?php echo $this->adminFormElement()->nameToId($numCurrentBlocksName); ?>',
                                        '<?php echo $this->adminFormElement()->nameToId($numNewBlocksName); ?>',
                                        'en',
                                        'en',
                                        ['en']);">Add block</a></p>

                                <input type="hidden" name="<?php echo $numCurrentBlocksName; ?>" value="<?php echo count($blockSequence->get('blocks')); ?>" id="<?php echo $this->adminFormElement()->nameToId($numCurrentBlocksName); ?>">
                                <input type="hidden" name="<?php echo $numNewBlocksName; ?>" value="0" id="<?php echo $this->adminFormElement()->nameToId($numNewBlocksName); ?>">

                            </div>
                        </div>
                        <?php endforeach; ?>

                    </fieldset>
                    <?php endif; ?>

                    <fieldset>
                        <legend>Submit</legend>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-2">

                                <?php
                                $form->get('preview')->setAttribute('class', 'btn btn-default');
                                echo $this->formElement($form->get('preview'));
                                ?>

                                <?php
                                $form->get('publish')->setAttribute('class', 'btn btn-success');
                                echo $this->formElement($form->get('publish'));
                                ?>

                            </div>
                        </div>

                    </fieldset>

                <?php echo $this->form()->closeTag() ?>

            </div>
        </div>
